version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed. Preparing to deploy...
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - node_modules/**/*
    