Resources:
  noegDubetonVitrine:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: noeg-dubeton-vitrine-2
      WebsiteConfiguration:
        IndexDocument: index.html

  noegDubetonVitrinePolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref noeg-dubeton-vitrine-2
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::${noeg-dubeton-vitrine-2}/*'
            Principal: '*'

  NoegWebPageRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: e5estiam.com.
      Name: noegdubetonvitrine.e5estiam.com.
      Type: A
      AliasTarget:
        DNSName: !GetAtt noeg-dubeton-vitrine-2.WebsiteURL
        HostedZoneId: Z21DNDUVLTQW6Q 

Outputs:
  WebsiteURL:
    Description: URL of the static website.
    Value: !GetAtt noeg-dubeton-vitrine-2.WebsiteURL