Resources:
  NoeGamingDynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  NoeGamingRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: goegamingapi
  NoeGamingRestApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - NoeGamingApiGatewayMethod
    Properties:
      RestApiId: !Ref NoeGamingRestApi
      StageName: test
  NoeGamingApiGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt 
        - NoeGamingRestApi
        - RootResourceId
      PathPart: NoeGaming
      RestApiId: !Ref NoeGamingRestApi
  NoeGamingApiGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    DependsOn:
      - NoeGamingFunctionApiGatewayPermission
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - NoeGamingFunction
              - Arn
            - /invocations
      ResourceId: !Ref NoeGamingApiGatewayResource
      RestApiId: !Ref NoeGamingRestApi
  NoeGamingFunctionApiGatewayPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - NoeGamingFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref NoeGamingRestApi
          - /*/*
  NoeGamingFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AppendToLogsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  NoeGamingFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              isBase64Encoded: false,
              statusCode:      200,
              headers:         { "content-type": "text/plain"},
              body:            `Your request:\n\n${JSON.stringify(event)}`
            }
          }
      Handler: index.handler
      Role: !GetAtt 
        - NoeGamingFunctionRole
        - Arn
      Runtime: nodejs20.x
  NoeGamingPostApiGateway:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - NoeGamingFunction
              - Arn
            - /invocations
      ResourceId: !Ref NoeGamingApiGatewayResource
      RestApiId: !Ref NoeGamingRestApi
    DependsOn:
      - NoeGamingFunctionApiGatewayPermission
Outputs:
  ApiUrl:
    Description: URL of the REST API.
    Value: !Join 
      - ''
      - - 'https://'
        - !Ref NoeGamingRestApi
        - .execute-api.
        - !Ref 'AWS::Region'
        - .
        - !Ref 'AWS::URLSuffix'
        - /test